// Objective-C API for talking to github.com/xtls/libxray Go package.
//   gobind -lang=objc github.com/xtls/libxray
//
// File is generated by gobind. Do not edit.

#ifndef __LibXray_H__
#define __LibXray_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class LibXrayAgeDecryptConfig;
@class LibXrayConvertShareLinksToXrayJsonRequest;
@class LibXrayConvertXrayJsonToShareLinksRequest;
@class LibXrayConvertXrayJsonToShareLinksResponse;
@class LibXrayCountGeoDataRequest;
@class LibXrayGenerateAgeKeyPairRequest;
@class LibXrayGenerateAgeKeyPairResponse;
@class LibXrayGetFreePortsRequest;
@class LibXrayGetFreePortsResponse;
@class LibXrayGetXrayStateResponse;
@class LibXrayLibXrayInvokeRequest;
@class LibXrayPingBatchItemRequest;
@class LibXrayPingBatchItemResponse;
@class LibXrayPingBatchRequest;
@class LibXrayPingBatchResponse;
@class LibXrayRunXrayRequest;
@class LibXrayTestXrayRequest;
@class LibXrayXrayVersionResponse;

@interface LibXrayAgeDecryptConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull secretKey;
@end

@interface LibXrayConvertShareLinksToXrayJsonRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull text;
@property (nonatomic) LibXrayAgeDecryptConfig* _Nullable age;
@end

@interface LibXrayConvertXrayJsonToShareLinksRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull xrayJson;
@end

@interface LibXrayConvertXrayJsonToShareLinksResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull links;
@end

@interface LibXrayCountGeoDataRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull name;
@property (nonatomic) NSString* _Nonnull geoType;
@property (nonatomic) NSString* _Nonnull datDir;
@end

@interface LibXrayGenerateAgeKeyPairRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field GenerateAgeKeyPairRequest.KeyType with unsupported type: github.com/xtls/libxray.AgeKeyType

@end

@interface LibXrayGenerateAgeKeyPairResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull secretKey;
@property (nonatomic) NSString* _Nonnull publicKey;
@end

@interface LibXrayGetFreePortsRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long count;
@end

@interface LibXrayGetFreePortsResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field GetFreePortsResponse.Ports with unsupported type: []int

@end

@interface LibXrayGetXrayStateResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) BOOL running;
@end

@interface LibXrayLibXrayInvokeRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long apiVersion;
// skipped field LibXrayInvokeRequest.Method with unsupported type: github.com/xtls/libxray.LibXrayMethod

// skipped field LibXrayInvokeRequest.Payload with unsupported type: encoding/json.RawMessage

@end

@interface LibXrayPingBatchItemRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull xrayJson;
@property (nonatomic) NSString* _Nonnull outboundTag;
@end

@interface LibXrayPingBatchItemResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) BOOL success;
@property (nonatomic) int64_t delay;
@property (nonatomic) NSString* _Nonnull error;
@end

@interface LibXrayPingBatchRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field PingBatchRequest.Configs with unsupported type: []github.com/xtls/libxray.PingBatchItemRequest

@property (nonatomic) long timeout;
@property (nonatomic) NSString* _Nonnull url;
@end

@interface LibXrayPingBatchResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field PingBatchResponse.Results with unsupported type: []github.com/xtls/libxray.PingBatchItemResponse

@end

@interface LibXrayRunXrayRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull xrayJson;
@end

@interface LibXrayTestXrayRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull xrayJson;
@end

@interface LibXrayXrayVersionResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull version;
@end

// skipped const AgeKeyTypeHybrid with unsupported type: github.com/xtls/libxray.AgeKeyType

// skipped const AgeKeyTypeX25519 with unsupported type: github.com/xtls/libxray.AgeKeyType

FOUNDATION_EXPORT const int64_t LibXrayLibXrayAPIVersion;
// skipped const LibXrayMethodConvertShareLinksToXrayJson with unsupported type: github.com/xtls/libxray.LibXrayMethod

// skipped const LibXrayMethodConvertXrayJsonToShareLinks with unsupported type: github.com/xtls/libxray.LibXrayMethod

// skipped const LibXrayMethodCountGeoData with unsupported type: github.com/xtls/libxray.LibXrayMethod

// skipped const LibXrayMethodGenerateAgeKeyPair with unsupported type: github.com/xtls/libxray.LibXrayMethod

// skipped const LibXrayMethodGetFreePorts with unsupported type: github.com/xtls/libxray.LibXrayMethod

// skipped const LibXrayMethodGetXrayState with unsupported type: github.com/xtls/libxray.LibXrayMethod

// skipped const LibXrayMethodPingBatch with unsupported type: github.com/xtls/libxray.LibXrayMethod

// skipped const LibXrayMethodRunXray with unsupported type: github.com/xtls/libxray.LibXrayMethod

// skipped const LibXrayMethodStopXray with unsupported type: github.com/xtls/libxray.LibXrayMethod

// skipped const LibXrayMethodTestXray with unsupported type: github.com/xtls/libxray.LibXrayMethod

// skipped const LibXrayMethodXrayVersion with unsupported type: github.com/xtls/libxray.LibXrayMethod


FOUNDATION_EXPORT NSString* _Nonnull LibXrayInvoke(NSString* _Nullable requestJSON);

#endif
